name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: build
      run: |
        luarocks install busted
        luarocks install busted-htest
        luarocks make

    - name: test
      run: |
        busted -o htest
